### ISSUE TITLE
Everyone add their name and role to the Contributors.md file

### ISSUE THREAD

**Issue by arronlacey** [21Monica02/CardioNLP#6]
Practice a Pull Request by adding your name and role to the Contributors.md file. Ask someone on the Team to be a Reviewer. 

1. Create a branch
2. Make change to the Contributors.md file
3. Stage the file
4. Commit the file with a message
5. In Gitkraken you can then grab the branch and drop into on top of the main branch
6. Select the bottom option "merge and create a pull request"
7. Add any Reviewers that you want to see the change

**Comment by 21Monica02** [comment]
Updated with my details
